version: '3.4'

services:
  datamicroservice:
    image: ${DOCKER_REGISTRY-}datamicroservice
    container_name: datamicroservice
    ports:
        - 52800:80
    expose:
        - 51800
        - 80
    depends_on:
        - redis-api
    links:
        - redis-api 
    build:
      context: .
      dockerfile: DataMicroservice/Dockerfile

  hightempandhumiditysensorms:
    image: ${DOCKER_REGISTRY-}hightempandhumiditysensorms
    container_name: hightempandhumiditysensorms
    ports:
        - 52804:80
    links:
        - datamicroservice
    depends_on:
        - datamicroservice
    build:
      context: .
      dockerfile: HighTempAndHumiditySensorMS/Dockerfile


  stableconditionssensorms:
    image: ${DOCKER_REGISTRY-}stableconditionssensorms
    container_name: stableconditionssensorms
    ports:
        - 52805:80
    links:
        - datamicroservice
    depends_on:
        - datamicroservice
    build:
      context: .
      dockerfile: StableConditionsSensorMS/Dockerfile

  redis-api:
    image: redis:latest

  redis-api-analytics:
    image: redis:latest

  analyticsmicroservice:
    image: ${DOCKER_REGISTRY-}analyticsmicroservice
    ports:
        - 52806:80
    links:
        - datamicroservice
        - redis-api-analytics
    depends_on:
        - datamicroservice
        - redis-api-analytics
    build:
      context: .
      dockerfile: AnalyticsMicroservice/Dockerfile

  emqx:
    image: 'emqx/emqx:latest'

  kuiper:
    image: 'emqx/kuiper:1.2.0-alpine'
    environment:
      MQTT_SOURCE__DEFAULT__SERVERS: "[tcp://emqx:1883]"
    depends_on:
        - datamicroservice
        - emqx


