version: '3.4'

services:
  hightempandhumiditysensorms:
    image: ${DOCKER_REGISTRY-}hightempandhumiditysensorms
    build:
      context: .
      dockerfile: HighTempAndHumiditySensorMS/Dockerfile
