version: '3.4'

services:
  datamicroservice:
    image: ${DOCKER_REGISTRY-}datamicroservice
    environment:
      - DataUrl=http://datamicroservice
      - RedisUrl=http://redis-api
    ports:
      - "51803:80"
    depends_on:
      - redis-api
    build:
      context: .
      dockerfile: DataMicroservice/Dockerfile

      
  hightempandhumiditysensorms:
    image: ${DOCKER_REGISTRY-}hightempandhumiditysensorms
    ports:
      - "51804:80"
    depends_on:
      - datamicroservice
    build:
      context: .
      dockerfile: HighTempAndHumiditySensorMS/Dockerfile
      
  stableconditionssensorms:
    image: ${DOCKER_REGISTRY-}stableconditionssensorms
    ports:
      - "51805:80"
    depends_on:
      - datamicroservice
    build:
      context: .
      dockerfile: StableConditionsSensorMS/Dockerfile

  redis-api:
        image: redis
      